apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep
  labels:
    app: test-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    containers:
      - name: nginx
        images: nginx:stable-alpine-perl
        ports:
          - name: nginx-port
            protocol: TCP
            containerPort: 80

